### PR TITLE
Use data() to harden the code

### LINKED ISSUE #833: Dangerous pointer acquisition through vector dereference
In C++, using `&my_vector[0]` to get a pointer to the underlying data causes undefined behavior if the vector is empty. This is because `my_vector[0]` dereferences the first value in the vector. The safe way to acquire a pointer to the underlying vector data is to do `my_vector.data()`, which returns a pointer without dereferencing any items in the vector.

Using `&my_vector[0]` to acquire a pointer to the underlying data caused a crash in 2D `__matmul__` when sizes `[N x 0] @ [0 x M]` were multiplied. It has been fixed in the matmul methods, but there are more candidates for this slightly dangerous pointer-acquisition strategy scattered throughout the codebase.

### Remaining dereferences (`rg "&[a-z_.]*\[" src/`):
Most of these matches are likely benign, since vector-size checks are scattered throughout the codebase. Still, if acquiring a pointer to the underlying data is what is meant, using the "canonical" pointer-acquiring function `.data()` is probably the way to go as it is safer. 

```
src/apyfixed.h
401:45:        apy_inplace_subtraction_single_limb(&init_max._data[0], limbs, 1);

src/apyfloat_util.h
1746:31:    man[0] = _umul128(mx, my, &man[1]);

src/apytypes_mp.h
40:55:        add_single_limbs_with_carry(src0[i], src1[i], &dest[i], carry, &carry);
90:54:        add_single_limbs_with_carry(src[i], dest[i], &dest[i], carry, &carry);
159:54:        sub_single_limbs_with_carry(dest[i], src[i], &dest[i], carry, &carry);
178:54:        sub_single_limbs_with_carry(src[i], dest[i], &dest[i], carry, &carry);
199:55:        sub_single_limbs_with_carry(src0[i], src1[i], &dest[i], carry, &carry);

src/apybuffer.h
116:20:            (void*)&_data[0],                // void       *buf
123:26:            (Py_ssize_t*)&_shape[0],         // Py_ssize_t *shape
124:26:            (Py_ssize_t*)&_strides[0],       // Py_ssize_t *strides

src/python_util.h
118:36:    apy_limb_t* limb_vec_tmp_ptr = &limb_vec[0];
172:32:    assert(limb_vec_tmp_ptr == &limb_vec[0] + limb_vec_size);
307:36:    apy_limb_t* limb_vec_tmp_ptr = &limb_vec_abs[0];
361:32:    assert(limb_vec_tmp_ptr == &limb_vec_abs[0] + limb_vec_size);

src/apyfixedarray.cc
157:24:            src1_ptr = &_data[0];
158:24:            src2_ptr = &rhs._data[0];
169:24:            src1_ptr = &result._data[0];
170:24:            src2_ptr = &rhs._data[0];
181:24:            src1_ptr = &_data[0];
182:24:            src2_ptr = &result._data[0];
186:17:                &result._data[i], // dst
217:13:            &result._data[i], // dst
218:13:            &result._data[i], // src1
219:13:            &imm._data[i],    // src2
280:13:            &result._data[i], // dst
281:13:            &result._data[i], // src1
282:13:            &imm._data[0],    // src2
367:17:                &result._data[i], // dst/src2
368:17:                &imm._data[0],    // src1
479:17:                &res_tmp_vec[0], // dst
487:17:                &res_tmp_vec[0], // dst
571:13:            &result._data[i * result._itemsize], // Quotient
572:13:            &abs_num[0],                         // Numerator
574:13:            &abs_den[0],                         // Denominator
626:30:    auto inv = APyDivInverse(&abs_den[0], den_significant_limbs);
630:34:        = apy_inplace_left_shift(&abs_den[0], den_significant_limbs, inv.norm_sh [... 0 more matches]
641:25:        auto quotient = &result._data[i * result._itemsize];
645:13:            &abs_num[0],           // Numerator
647:13:            &abs_den[0],           // Denominator
716:13:            &result._data[i * result._itemsize], // Quotient
717:13:            &abs_num[0],                         // Numerator
719:13:            &abs_den[0],                         // Denominator
1327:69:    return nb::ndarray<NB_ARRAY_TYPE, INT_TYPE>(result_data, _ndim, &_shape[0],  [... 0 more matches]

src/apyfixed_util.h
497:58:            apy_inplace_addition(&*it_begin, src_nlimbs, &rnd_words[0], limbs_to [... 0 more matches]
899:13:            &prod_abs[0], &op2_abs[0], src2_limbs, &op1_abs[0], src1_limbs
903:13:            &prod_abs[0], &op1_abs[0], src1_limbs, &op2_abs[0], src2_limbs
1172:57:                apy_inplace_addition_same_length(&*acc, &product[0], dst_limbs); [... 0 more matches]
1591:46:            apy_inplace_addition_same_length(&acc_it[0], &src_it[0], src_limbs); [... 0 more matches]
1595:34:            apy_inplace_addition(&acc_it[0], acc_limbs, &src_it[0], src_limbs);
1655:46:            apy_inplace_addition_same_length(&acc_it[0], &src_it[0], limbs);
1656:46:            apy_inplace_addition_same_length(&acc_it[limbs], &src_it[limbs], lim [... 0 more matches]
1662:34:            apy_inplace_addition(&acc_it[0], acc_limbs, &src_it[0], src_limbs);
1663:34:            apy_inplace_addition(&acc_it[acc_j], acc_j, &src_it[src_j], src_j);

src/apyfixed.cc
144:13:            &result._data[0],    // dst
145:13:            &result._data[0],    // src1
146:13:            &operand[0],         // src2
249:9:        &result._data[0],                          // Quotient
515:9:        &_data[0],    // dst
718:9:        &data[0],   // dst
722:9:        &data[0],    // dst/src

src/apytypes_util.h
221:36:        if (apy_inplace_left_shift(&data[0], data.size(), 1)) {
243:45:        limb_out |= apy_inplace_right_shift(&data[0], data.size(), 1);
284:32:        apy_inplace_left_shift(&nibble_data[0], nibble_data.size(), 1);
331:48:            new_limb = apy_inplace_right_shift(&nibble_data[0], nibble_data.size [... 0 more matches]
351:33:        apy_inplace_right_shift(&nibble_data[0], nibble_data.size(), shft_val);
366:46:    auto shift_out = apy_inplace_right_shift(&bcd_list[0], bcd_list.size(), 1);
394:45:    auto shift_out = apy_inplace_left_shift(&bcd_list[0], bcd_list.size(), 1);

src/apyfloatarray.cc
127:9:    add(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
143:9:    add(&_data[0], &rhs_data, &res._data[0], res._nitems);
162:9:    sub(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
178:9:    sub(&_data[0], &rhs_data, &res._data[0], res._nitems);
215:9:    mul(&_data[0], &rhs._data[0], &res._data[0], _nitems);
232:9:    mul(&_data[0], &rhs_data, &res._data[0], _nitems);
251:9:    div(&_data[0], &rhs._data[0], &res._data[0], _nitems);
268:9:    div(&_data[0], &rhs_data, &res._data[0], _nitems);
284:20:    div(&lhs_data, &_data[0], &res._data[0], _nitems);
300:20:    sub(&lhs_data, &_data[0], &res._data[0], _nitems);
1110:70:    return nb::ndarray<NB_ARRAY_TYPE, INT_TYPE>(result_data, ndim(), &_shape[0], [... 0 more matches]
1561:9:        &_data[0],     // src1, a: [1 x N]
1562:9:        &rhs._data[0], // src2, b: [N x 1]

src/apyarray.h
1941:51:        return nb::ndarray<CXX_TYPE>(data, _ndim, &_shape[0], owner);

src/apycfixedarray.cc
181:24:            src1_ptr = &_data[0];
182:24:            src2_ptr = &rhs._data[0];
193:24:            src1_ptr = &result._data[0];
194:24:            src2_ptr = &rhs._data[0];
205:24:            src1_ptr = &_data[0];
206:24:            src2_ptr = &result._data[0];
210:17:                &result._data[i],    // dst
241:13:            &result._data[i],    // dst
242:13:            &result._data[i],    // src1
243:13:            &imm._data[i],       // src2
309:13:            &result._data[i],    // dst
310:13:            &result._data[i],    // src1
311:13:            &imm._data[0],       // src2
315:13:            &result._data[i + result._itemsize / 2], // dst
316:13:            &result._data[i + result._itemsize / 2], // src1
317:13:            &imm._data[0 + result._itemsize / 2],    // src2
412:13:            &result._data[i],                         // dst/src2
413:13:            &imm._data[0],                            // src1
417:13:            &result._data[i + result._itemsize / 2],  // dst(src2)
418:13:            &imm._data[0 + result._itemsize / 2],     // src1
458:17:                &result._data[2 * i], &_data[i], &rhs._data[i]

src/apytypes_mp.cc
625:17:                &numerator[i], denominator, denominator_limbs, quotient_tmp
636:17:                &numerator[i], denominator, denominator_limbs - 2, quotient_tmp
648:36:                                   &numerator[i],
713:13:            &norm_denominator[0], denominator, denominator_limbs, inv.norm_shift [... 0 more matches]
721:13:            &norm_denominator[0],

src/apycfloatarray.cc
508:9:    add(&_data[0], &rhs._data[0], &res._data[0], 2 * res._nitems);
523:9:    add(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
543:9:    sub(&_data[0], &rhs._data[0], &res._data[0], 2 * res._nitems);
558:9:    sub(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
581:9:    sub(&lhs._data[0], &_data[0], &res._data[0], _nitems);
600:9:    mul(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
616:9:    mul(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
635:9:    div(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
650:9:    div(&_data[0], &rhs._data[0], &res._data[0], res._nitems);
664:9:    div(&lhs._data[0], &_data[0], &res._data[0], _nitems);
1112:9:        &_data[0],     // src1, a: [1 x N]
1113:9:        &rhs._data[0], // src2, b: [N x 1]

src/apycfixed_util.h
226:38:    apy_inplace_addition_same_length(&den_imm[0], &prod_imm[0], 2 * src2_limbs); [... 0 more matches]
257:38:    apy_inplace_addition_same_length(&prod_imm[0], &prod_imm[0] + prod_len, prod [... 0 more matches]
267:9:        &qte_imm[0],          // Quotient
268:9:        &num_imm[0],          // Numerator
270:9:        &den_imm[0],          // Denominator
308:9:        &prod_imm[0], &prod_imm[0] + prod_len, prod_len
319:9:        &qte_imm[0],          // Quotient
320:9:        &num_imm[0],          // Numerator
322:9:        &den_imm[0],          // Denominator
480:45:                apy_subtraction_same_length(&ac_bd[0], &ac[0], &bd[0], 2);
481:42:                apy_addition_same_length(&bc_ad[0], &bc[0], &ad[0], 2);
484:50:                apy_inplace_addition_same_length(&acc[0], &ac_bd[0], 2);
485:50:                apy_inplace_addition_same_length(&acc[2], &bc_ad[0], 2);
584:21:                    &acc[0 * dst_limbs],
585:21:                    &product[0 * product_limbs],
589:21:                    &acc[1 * dst_limbs],
590:21:                    &product[1 * product_limbs],

src/apycfixed.cc
238:42:            complex_multiplication_1_1_2(&result._data[0], &_data[0], &rhs._data [... 0 more matches]
```

### PR DESCRIPTION
**Pull request by oscargus**
# PR Summary

Closes #833

Still some cases where the pattern is used, but they cannot be replace the way the code is right now. I guess that the cases in `apyfixed_util` can be changed if lambdas are typed differently (not `auto`), but not sure what it should be etc. The iterator/vector-stuff I do not really understand (pointers on the other hand...).

## PR Checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is tested
- [N/A] relevant changes added to [CHANGELOG.md](https://github.com/apytypes/apytypes/blob/main/CHANGELOG.md)
- [N/A] new functionality is documented

### CODE REVIEW

File: src/apycfixedarray.cc [hunk 1]
```diff
@@ -322,7 +322,7 @@ APyCFixedArray::_apycfixed_base_add_sub(const APyCFixed& rhs) const
         ripple_carry_op {}(      // real part
             &result._data[i],    // dst
             &result._data[i],    // src1
```
Comment (miklhh) [inline src/apycfixedarray.cc]: These should be `result._data.data() + i`

File: src/apyfixed_util.h [hunk 2]
```diff
@@ -895,11 +897,11 @@ static APY_INLINE void fixed_point_product(
     // Perform the multiplication of absolute values
     if (src1_limbs < src2_limbs) {
         apy_unsigned_multiplication(
-            &prod_abs[0], &op2_abs[0], src2_limbs, &op1_abs[0], src1_limbs
+            prod_abs.data(), &op2_abs[0], src2_limbs, &op1_abs[0], src1_limbs
         );
     } else {
         apy_unsigned_multiplication(
-            &prod_abs[0], &op1_abs[0], src1_limbs, &op2_abs[0], src2_limbs
+            prod_abs.data(), &op1_abs[0], src1_limbs, &op2_abs[0], src2_limbs
```
Comment (miklhh) [inline src/apyfixed_util.h]: `op1_abs` and `op2_abs`

File: src/apycfixed_util.h [hunk 3]
```diff
@@ -477,12 +479,12 @@ struct ComplexFixedPointInnerProduct {
...
                 auto&& ad = tuple_to_array(long_signed_mult(z1.real(), z2.imag()));
-                apy_subtraction_same_length(&ac_bd[0], &ac[0], &bd[0], 2);
-                apy_addition_same_length(&bc_ad[0], &bc[0], &ad[0], 2);
+                apy_subtraction_same_length(ac_bd.data(), ac.data(), bd.data(), 2);
+                apy_addition_same_length(bc_ad.data(), bc.data(), ad.data(), 2);
 
                 // Perform accumulation
-                apy_inplace_addition_same_length(&acc[0], &ac_bd[0], 2);
-                apy_inplace_addition_same_length(&acc[2], &bc_ad[0], 2);
+                apy_inplace_addition_same_length(acc.data(), ac_bd.data(), 2);
```
Comment (miklhh) [inline src/apycfixed_util.h]: I guess this `acc` is of iterator type and so it doesn't have a `data()` method for retrieving a pointer to the underlying data. At least that's what the MSVC compiler is complaining about.

Take back `&acc[0]` here. We know that `acc[0]` can be dereferenced from how this method is called. If `acc` holds zero elements, calling this function UB anyway. Same thing is true about `acc[2]`, if that element doesn't exist, calling this function is UB.

**Review by miklhh — COMMENTED** [review]
Thanks for fixing this issue! ❤️
