### PR TITLE
Fix cast example for APyFixed

### LINKED ISSUE #609: Incorrect cast example for APyFixed
https://apytypes.github.io/apytypes/api/apyfixed.html#apytypes.APyFixed.cast

Truncation and rounding gives the same, although the text says that they do not.

### PR DESCRIPTION
**Pull request by Theodor-Lindberg**
# PR Summary

Closes #609.

# PR Checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is tested
- [N/A] relevant changes added to [CHANGELOG.md](https://github.com/apytypes/apytypes/blob/main/CHANGELOG.md)
- [N/A] new functionality is documented

### CODE REVIEW

File: src/apyfixed_wrapper.cc [hunk 1]
```diff
@@ -242,7 +242,7 @@ void bind_fixed(nb::module_& m)
             Rounding (2.25)
 
             >>> fx.cast(int_bits=3, frac_bits=2, quantization=QuantizationMode.RND) # doctest: +SKIP
```
Comment (miklhh) [inline src/apyfixed_wrapper.cc:244]: Why is `# doctest: +SKIP` used here?

Comment (Theodor-Lindberg) [reply src/apyfixed_wrapper.cc:244]: I don't know, I only updated the value. I can try running it without `# doctest: +SKIP`.

Comment (miklhh) [reply src/apyfixed_wrapper.cc]: Please do! :)

Comment (Theodor-Lindberg) [reply src/apyfixed_wrapper.cc]: Seems fine! I'll go ahead and merge it.

**Comment by oscargus** [comment]
Ahh, there was a doctest-skip... Good that it wasn't an actual bug... Thanks!
