### PR TITLE
Fix multiplication between normal and subnormal numbers

### LINKED ISSUE #319: Sub-normal multiplication with one not correct
There is an xfail-test added in #318 that multiplies all (non-nan/inf)-numbers with 1.

Not sure if it was introduced in the speed-up or if it was there earlier.

### PR DESCRIPTION
**Pull request by Theodor-Lindberg**
Fixes #319.

* [x] Scalar fixed
* [x] Array fixed

### CODE REVIEW

File: src/apyfloatarray.cc [hunk 1]
```diff
@@ -563,22 +564,27 @@ APyFloatArray APyFloatArray::operator*(const APyFloatArray& rhs) const
...
-                        | ((new_man & ((1 << -tmp_exp) - 1)) != 0);
-                    tmp_exp = 0;
                 } else {
-                    // Align with longer result
                     new_man <<= 2;
                 }
+            } else {
+                // One or two of the operands were subnormal
+                new_man <<= std::max(tmp_exp + 1, (std::int64_t)0);
+                tmp_exp = 0;
```
Comment (oscargus) [inline src/apyfloatarray.cc:581]: I do not think this is correct. This is basically the case where we would like to shift-out parts of the mantissa and by setting tmp_exp to zero this will not happen. Probably the cause of #353.

Comment (Theodor-Lindberg) [reply src/apyfloatarray.cc:581]: Hm yes that is probably the cause for #353. That line was intended to handle #319 but seems to have broken other things.
